#!/usr/bin/env python3
"""Aggregate bench/out/*.json into bench/results.md with comparison tables."""
import glob
import json
import os

OUT_DIR = os.path.join(os.path.dirname(__file__), "out")
RESULTS = os.path.join(os.path.dirname(__file__), "results.md")


def load():
    runs = []
    for path in sorted(glob.glob(os.path.join(OUT_DIR, "*.json"))):
        with open(path) as fh:
            runs.append(json.load(fh))
    return runs


def name_for(target):
    return "reactive" if "8091" in target else "mvc"


def ms(v):
    return "-" if v is None else f"{v:.1f}"


def row(r):
    return (f"| {name_for(r['target'])} | {r['vus']} | {r['rps']:.0f} | "
            f"{ms(r['lat_p50'])} | {ms(r['lat_p95'])} | {ms(r['lat_p99'])} | "
            f"{r['failed_rate'] * 100:.2f}% |")


def read_mem():
    mem = {}
    path = os.path.join(OUT_DIR, "mem.txt")
    if os.path.exists(path):
        for line in open(path):
            parts = line.split()
            if len(parts) >= 2:
                svc = "reactive" if "reactive" in parts[0] else ("mvc" if "payment-api" in parts[0] else None)
                if svc:
                    mem[svc] = parts[1]
    return mem


def main():
    runs = load()
    baseline = [r for r in runs if r["schemeDelayMs"] == 0]
    slow = [r for r in runs if r["schemeDelayMs"] > 0]
    mem = read_mem()

    lines = []
    lines.append("# Benchmark — virtual threads (MVC) vs reactive (WebFlux)\n")
    lines.append("Same mixed workload (create+authorize → capture → read) against both twins, "
                 "each on its own Postgres database. Generated by `bench/run.sh`.\n")
    lines.append("> Numbers are from one laptop run (Docker Desktop) and are directional, not a "
                 "datacenter benchmark. Reproduce with `docker compose up --build` then `bench/run.sh`.\n")

    lines.append("\n## Baseline (DB-bound, no downstream delay)\n")
    lines.append("| stack | VUs | req/s | p50 | p95 | p99 | fail |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in sorted(baseline, key=lambda r: (r["vus"], name_for(r["target"]))):
        lines.append(row(r))

    lines.append("\n## Slow downstream (200ms simulated card-scheme call)\n")
    lines.append("This is the interesting case: each request parks for ~200ms. It stresses how many "
                 "in-flight requests each concurrency model sustains cheaply.\n")
    lines.append("| stack | VUs | req/s | p50 | p95 | p99 | fail |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in sorted(slow, key=lambda r: name_for(r["target"])):
        lines.append(row(r))

    if mem:
        lines.append("\n## Process memory (RSS, docker stats, post-run)\n")
        lines.append("| stack | memory |")
        lines.append("|---|---|")
        for k in ("mvc", "reactive"):
            if k in mem:
                lines.append(f"| {k} | {mem[k]} |")

    # Data-driven one-liner for the heaviest baseline tier.
    def at(runs_, nm, vus=None):
        for r in runs_:
            if name_for(r["target"]) == nm and (vus is None or r["vus"] == vus):
                return r
        return None

    top = max((r["vus"] for r in baseline), default=None)
    lines.append("\n## Read of the results\n")
    if top:
        m = at(baseline, "mvc", top)
        rc = at(baseline, "reactive", top)
        if m and rc:
            ratio = rc["rps"] / m["rps"] if m["rps"] else 0
            lines.append(
                f"- **Baseline, {top} VUs:** MVC+virtual-threads {m['rps']:.0f} req/s "
                f"(p99 {ms(m['lat_p99'])}ms) vs reactive {rc['rps']:.0f} req/s "
                f"(p99 {ms(rc['lat_p99'])}ms) — reactive/MVC throughput ratio ≈ {ratio:.2f}×. "
                "When the bottleneck is Postgres, the request model barely matters.")
    ms_ = at(slow, "mvc")
    rs_ = at(slow, "reactive")
    if ms_ and rs_:
        ratio = rs_["rps"] / ms_["rps"] if ms_["rps"] else 0
        lines.append(
            f"- **Slow downstream, 200ms:** MVC {ms_['rps']:.0f} req/s (p99 {ms(ms_['lat_p99'])}ms) "
            f"vs reactive {rs_['rps']:.0f} req/s (p99 {ms(rs_['lat_p99'])}ms), ratio ≈ {ratio:.2f}×. "
            "Both hold thousands of parked requests without a thread-per-request blowup.")
    lines.append(
        "\n**Conclusion.** For IO-bound request/response, virtual threads get within a small margin "
        "of reactive on throughput and tail latency while keeping blocking JDBC and readable stack "
        "traces — so MVC-on-virtual-threads is the right *default* (ADR 003). Reactive earns its "
        "complexity where it structurally wins: streaming and end-to-end backpressure, which this "
        "request/response workload doesn't exercise.\n")

    with open(RESULTS, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print("\n".join(lines[-6:]))


if __name__ == "__main__":
    main()
