global:
  scrape_interval: 15s

scrape_configs:
  - job_name: paylane-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - payment-api:8081
          - payment-api-reactive:8091
          - ledger:8082
          - settlement-worker:8083
        labels:
          stack: paylane
